.common_settings: &common_settings
  port: 22
  identityFile: ~/.ssh/id_rsa
  forwardAgent: true
  multiplexing: true
  options:
    - UserKnownHostsFile=/dev/null
    - StrictHostKeyChecking=no
  roles:
    - app
    - db

127.0.0.1:
  <<: *common_settings
  hostname: 127.0.0.1
  user: vikram
  stage: staging
  deploy_path: /home/vikram/my_project
